services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: twenty-one-backend-dev
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - '4000:4000'

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: twenty-one-frontend-dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - '3000:5173'
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
